name: Artifacts
on: [pull_request, workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - run: |
          zig build ci --summary all
      - run: |
          zig build ci -Dversion=3.11.13 --summary all
